network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no
      dhcp6: no
      # Remove addresses and routes from here
  bridges:
    br0:
      interfaces: [eno1]
      addresses:
        - 198.18.128.101/18
      nameservers:
        addresses: 
        - 8.8.8.8
        - 8.8.4.4  
      routes:
        - to: default
          via: 198.18.128.1
      parameters:
        stp: false
        forward-delay: 0

    ceos1-l01:
      dhcp4: no
      dhcp6: no
      
    ceos2-l02:
      dhcp4: no
      dhcp6: no